{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_shili.py:9: AssertionError"}, "start": 1642067392253, "stop": 1642067392253, "uuid": "4881011f-6131-4e2a-92bd-57ce6d21b204", "historyId": "c430492690611553bb2f7a80b81fef0e", "testCaseId": "06eef915a3ae6e5f8675944374b803c1", "fullName": "test_shili#test_answer", "labels": [{"name": "suite", "value": "test_shili"}, {"name": "host", "value": "DESKTOP-V45JC51"}, {"name": "thread", "value": "44332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_shili"}]}